### ISSUE TITLE
Parser fails with node names containing a logical operator

### ISSUE THREAD

**Issue by aurelien-naldi** [colomoto/pyMaBoSS#45]
I had some surprising errors when loading a MaBoSS model coming from GINsim or bioLQM through PyMaBoSS: it complained that some components are used but not defined, while these components are well defined in the bnd file. Loading the same model directly in MaBoSS works fine.

After some search, this happens when some other component (defined before the apparent culprit in the error message) has a "confusing" name. I had this problem with NOTCH and ORC. In both case, renaming the component in lower case (notch and orc) solved the issue. In both case the node name was starting with an upper case logical operator.

**Comment by aurelien-naldi** [comment]
Using the attached example file, the following python code
`masim = maboss.load("confused_parser.bnd")`

gives the following error:
`['BooleanNetwork exception: node B used but not defined']`

**Comment by aurelien-naldi** [comment]
[confused_parser.zip](https://github.com/colomoto/pyMaBoSS/files/5465627/confused_parser.zip)

**Comment by aurelien-naldi** [comment]
Looking briefly at the code in logic.py, it looks like this is only used in gsparser.py and removing the restrictions from varName may be a good enough fix.

@vincent-noel @pauleve : I'm not familiar with pyparsing, do you know how to adapt the definitions so that we allow a name which starts with a keyword but extends it?

To go further, I think that variable names should not be "true" or "false" (no matter if it is upper or lower case!) but operators should not be a problem as they appear in different part of expressions and no confusion is possible.

**Comment by vincent-noel** [comment]
I removed the restrictions, and it seems to work. 
I also added a check that identifiers (node's name, internal variable, variables) are not in the reserved list (true, false, not, and, or, xor, node). I added the operators to this list, because MaBoSS's compiler is doing the same. 

The pull request is here : #46

**Comment by aurelien-naldi** [comment]
This may be something to add as good practice to a future version of SBML qual spec. SBML itself only requires that identifiers are valid XML IDs, it would make sense for improved interoperability to exclude some keywords.

If we have some misleading identifiers in an SBML model, I think we could rename them as part of the sanitize modifier in bioLQM.
